// AGENCIAS/frontend/src/components/compras/checkout.svelte
<script>
  import { ComprasAPI } from '@/lib/api';
  import { navigate } from '@/lib/router';

  let tarjeta = { numero: '', cvv: '' };
  let facturacion = { direccion: '', ciudad: '', pais: '', zip: '' };
  let loading = false;
  let error = '';

  function luhnOk(num) {
    const s = (num || '').replace(/\s+/g, '');
    if (!/^\d{12,19}$/.test(s)) return false;
    let sum = 0, alt = false;
    for (let i = s.length - 1; i >= 0; i--) {
      let n = parseInt(s[i], 10);
      if (alt) { n *= 2; if (n > 9) n -= 9; }
      sum += n; alt = !alt;
    }
    return sum % 10 === 0;
  }

  function normalize() {
    tarjeta.numero = (tarjeta.numero || '').replace(/\s+/g, '');
    tarjeta.cvv = (tarjeta.cvv || '').trim();
    facturacion.direccion = (facturacion.direccion || '').trim();
    facturacion.ciudad = (facturacion.ciudad || '').trim();
    facturacion.pais = (facturacion.pais || '').trim();
    facturacion.zip = (facturacion.zip || '').trim();
  }

  function showErrorFrom(e) {
    try {
      if (e?.response?.data) {
        const d = e.response.data;
        if (typeof d === 'string') return d;
        if (d.detail) return typeof d.detail === 'string' ? d.detail : JSON.stringify(d.detail);
        if (d.error) return d.error;
      }
    } catch(_) {}
    if (e?.message) return e.message;
    return 'Error procesando el pago';
  }

  async function pagar() {
    error = '';
    normalize();

    if (!luhnOk(tarjeta.numero)) {
      error = 'Número de tarjeta inválido.'; return;
    }
    if (!/^\d{3,4}$/.test(tarjeta.cvv)) {
      error = 'CVV inválido.'; return;
    }

    loading = true;
    try {
      const r = await ComprasAPI.checkout({ tarjeta, facturacion });
      alert(`Compra exitosa. Reserva #${r.idReserva}`);
      navigate(`/reservas/${r.idReserva}`);
    } catch (e) {
      error = showErrorFrom(e);
    } finally {
      loading = false;
    }
  }

  function onEnter(e) {
    if (e.key === 'Enter' && !loading) pagar();
  }
</script>

<div class="container" role="form" on:keydown={onEnter}>
  <h2>Checkout</h2>
  {#if error}<p style="color:#E62727; margin:8px 0">{error}</p>{/if}

  <div class="card" style="display:grid; gap:12px; max-width:700px;">
    <div>
      <label class="label" for="numTarjeta">Número de tarjeta</label>
      <input
        id="numTarjeta"
        class="input"
        bind:value={tarjeta.numero}
        placeholder="4111 1111 1111 1111"
        inputmode="numeric"
        maxlength="23"
        on:input={(e)=> tarjeta.numero = e.target.value.replace(/[^\d ]/g,'')}
      />
      <small style="opacity:.7">No se guarda en el servidor.</small>
    </div>

    <div>
      <label class="label" for="cvv">CVV</label>
      <input
        id="cvv"
        class="input"
        bind:value={tarjeta.cvv}
        placeholder="123"
        inputmode="numeric"
        maxlength="4"
        on:input={(e)=> tarjeta.cvv = e.target.value.replace(/\D/g,'')}
      />
    </div>

    <div class="hr"></div>

    <div>
      <label class="label" for="direccion">Dirección</label>
      <input id="direccion" class="input" bind:value={facturacion.direccion} />
    </div>

    <div class="grid grid-2">
      <div>
        <label class="label" for="ciudad">Ciudad</label>
        <input id="ciudad" class="input" bind:value={facturacion.ciudad} />
      </div>
      <div>
        <label class="label" for="pais">País</label>
        <input id="pais" class="input" bind:value={facturacion.pais} />
      </div>
    </div>

    <div>
      <label class="label" for="zip">ZIP</label>
      <input id="zip" class="input" bind:value={facturacion.zip} />
    </div>

    <div>
      <button class="btn" disabled={loading} on:click={pagar}>
        {loading ? 'Procesando…' : 'Pagar'}
      </button>
    </div>
  </div>
</div>

<style>
  .btn[disabled]{ opacity:.7; cursor:not-allowed;}
</style>

// frontend/src/paginas/Checkout.jsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { comprasApi } from "../api/compras";
import { getUser } from "../lib/auth";
import RouteLine from "../components/RouteLine";
import "../styles/checkout.css";

const money = (n) => Number(n || 0).toLocaleString("es-GT", { style: "currency", currency: "GTQ" });

const luhn = (num) => {
  const s = String(num || "").replace(/\D/g, "");
  if (s.length < 12) return false;
  let sum = 0, alt = false;
  for (let i = s.length - 1; i >= 0; i--) {
    let n = parseInt(s[i], 10);
    if (alt) { n *= 2; if (n > 9) n -= 9; }
    sum += n; alt = !alt;
  }
  return sum % 10 === 0;
};

const formatCard = (val) =>
  String(val || "").replace(/\D/g, "").slice(0,19).replace(/(\d{4})(?=\d)/g,"$1 ");

export default function Checkout() {
  const nav = useNavigate();
  const u = getUser();

  const [cart, setCart] = useState(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");

  const [f, setF] = useState({
    nombre: u?.nombre || "",
    numero: "", expMes: "", expAnio: "", cvv: "",
    direccion: "", ciudad: "", pais: "", zip: "",
  });

  useEffect(() => {
    if (!u) { nav("/login"); return; }
    (async () => {
      try {
        setLoading(true);
        const { data } = await comprasApi.getCart();
        if (!data?.items?.length) { nav("/compras/carrito"); return; }
        setCart(data);
      } catch (e) {
        setErr(e?.response?.data?.error || e.message || "No se pudo cargar el carrito");
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const onChange = (e) => {
    const { name, value } = e.target;
    if (name === "numero") return setF(p => ({ ...p, numero: formatCard(value) }));
    if (name === "expMes")  return setF(p => ({ ...p, expMes:  value.replace(/\D/g,"").slice(0,2) }));
    if (name === "expAnio") return setF(p => ({ ...p, expAnio: value.replace(/\D/g,"").slice(0,4) }));
    if (name === "cvv")     return setF(p => ({ ...p, cvv:     value.replace(/\D/g,"").slice(0,4) }));
    setF(p => ({ ...p, [name]: value }));
  };

  const validar = () => {
    if (!f.nombre.trim()) return "Ingresa el nombre del titular.";
    const clean = f.numero.replace(/\s+/g,"");
    if (!luhn(clean)) return "Número de tarjeta inválido.";
    if (!/^\d{2}$/.test(f.expMes) || +f.expMes < 1 || +f.expMes > 12) return "Mes inválido.";
    if (!/^\d{2,4}$/.test(f.expAnio)) return "Año inválido.";
    const yy = f.expAnio.length === 2 ? ("20" + f.expAnio) : f.expAnio;
    const exp = new Date(+yy, +f.expMes, 0);
    if (exp < new Date()) return "Tarjeta expirada.";
    if (!/^\d{3,4}$/.test(f.cvv)) return "CVV inválido.";
    if (!f.direccion.trim() || !f.ciudad.trim() || !f.pais.trim()) return "Completa la dirección de cobro.";
    return null;
  };

  const onSubmit = async (e) => {
    e.preventDefault();
    const v = validar();
    if (v) { alert(v); return; }
    try {
      const payload = {
        tarjeta: {
          nombre: f.nombre.trim(),
          numero: f.numero.replace(/\s+/g, ""),
          expMes: Number(f.expMes),
          expAnio: Number(f.expAnio.length === 2 ? ("20" + f.expAnio) : f.expAnio),
          cvv: f.cvv,
        },
        facturacion: {
          direccion: f.direccion.trim(),
          ciudad: f.ciudad.trim(),
          pais: f.pais.trim(),
          zip: f.zip.trim(),
        },
      };
      const { data } = await comprasApi.checkout(payload);
      nav(`/compras/checkout/${data.idReserva}`);
    } catch (e2) {
      alert(e2?.response?.data?.error || e2.message || "No fue posible completar el pago");
    }
  };

  if (!u) return null;

  return (
    <div className="container checkout">
      <div className="grid">
        <div className="card">
          <h2>Pagar reserva</h2>
          <form className="form" onSubmit={onSubmit}>
            <label>Nombre del titular
              <input className="input" name="nombre" value={f.nombre} onChange={onChange} />
            </label>

            <label>Número de tarjeta
              <input
                className="input"
                name="numero"
                value={f.numero}
                onChange={onChange}
                placeholder="4111 1111 1111 1111"
                inputMode="numeric"
                autoComplete="cc-number"
              />
            </label>

            <div className="row">
              <label>Mes (MM)
                <input className="input" name="expMes" value={f.expMes}
                       onChange={onChange} placeholder="MM" inputMode="numeric" autoComplete="cc-exp-month" />
              </label>
              <label>Año (YY/AAAA)
                <input className="input" name="expAnio" value={f.expAnio}
                       onChange={onChange} placeholder="YY o AAAA" inputMode="numeric" autoComplete="cc-exp-year" />
              </label>
              <label>CVV
                <input className="input" name="cvv" value={f.cvv}
                       onChange={onChange} placeholder="3-4 dígitos" inputMode="numeric" autoComplete="cc-csc" />
              </label>
            </div>

            <label>Dirección
              <textarea className="input input--textarea" name="direccion" value={f.direccion} onChange={onChange} rows={3} />
            </label>
            <div className="row">
              <label>Ciudad
                <input className="input" name="ciudad" value={f.ciudad} onChange={onChange} />
              </label>
              <label>País
                <input className="input" name="pais" value={f.pais} onChange={onChange} />
              </label>
              <label>Código postal
                <input className="input" name="zip" value={f.zip} onChange={onChange} />
              </label>
            </div>

            <button className="btn btn-primary" type="submit" disabled={loading}>
              Confirmar y pagar
            </button>
          </form>
        </div>

        <div className="card">
          <h2>Resumen</h2>
          {loading ? (
            <>
              <div className="skl title" />
              <div className="skl row" />
              <div className="skl row" />
            </>
          ) : err ? (
            <div className="error">{err}</div>
          ) : (
            <>
              <ul className="sum-list">
                {cart?.items?.map((it) => (
                  <li key={it.idItem} className="sum-item">
                    <div>
                      <div><strong>{it.codigoVuelo}</strong> <span className="pill">{it.clase}</span></div>
                      <RouteLine item={it} />
                      <div className="label">{new Date(it.fechaSalida).toLocaleString("es-GT")}</div>
                    </div>
                    <div>{money(it.subtotal)}</div>
                  </li>
                ))}
              </ul>
              <div className="sum-total">
                Total: <strong>{money(cart?.total)}</strong>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
