// AGENCIAS/frontend/src/components/login.svelte
<script>
  import { onMount } from 'svelte';
  import { AuthAPI } from '../lib/api';
  import { setAuth, isLoggedIn } from '../lib/auth';
  import { navigate, path } from '../lib/router';

  let email = '';
  let password = '';
  let loading = false;
  let error = '';
  let showPwd = false;

  function nextFromLocation() {
    let q = '';
    if (location.hash.includes('?')) {
      q = location.hash.split('?')[1];
    } else if (location.search && location.pathname.endsWith('/login')) {
      q = location.search.slice(1);
    }
    const params = new URLSearchParams(q);
    const n = params.get('next');
    return n && n.startsWith('/') ? n : '/';
  }

  onMount(() => {
    if ($isLoggedIn) navigate('/');
  });

  $: if ($isLoggedIn && $path === '/login') {
    navigate('/');
  }

  async function submit(e) {
    e.preventDefault();
    error = '';
    loading = true;
    try {
      const res = await AuthAPI.login({ email: email.trim().toLowerCase(), password });
      setAuth({ token: res.access_token, user: res.user });
      navigate(nextFromLocation());
    } catch (e) {
      error = e?.message || 'Error al iniciar sesión';
    } finally {
      loading = false;
    }
  }
</script>

<div class="container" style="display:grid;place-items:center;min-height:calc(100vh - 64px);">
  <form class="card" style="width: 420px;" on:submit|preventDefault={submit} autocomplete="on">
    <h2 style="margin:0 0 10px 0;">Inicia sesión</h2>
    <p style="margin:0;color:#9ca3af">Usa tu correo y contraseña registrados.</p>

    <div style="margin-top:12px;">
      <label class="label" for="email">Correo</label>
      <input
        id="email"
        class="input"
        type="email"
        bind:value={email}
        placeholder="tucorreo@dominio.com"
        required
        autocomplete="email"
      />
    </div>

    <div style="margin-top:12px;">
      <label class="label" for="password">Contraseña</label>
      <div style="display:flex;gap:8px;align-items:center;">
        <input
          id="password"
          class="input"
          type={showPwd ? 'text' : 'password'}
          bind:value={password}
          placeholder="••••••••"
          required
          autocomplete="current-password"
        />
        <button
          type="button"
          class="btn"
          on:click={() => (showPwd = !showPwd)}
          aria-pressed={showPwd}
          aria-label={showPwd ? 'Ocultar contraseña' : 'Mostrar contraseña'}
        >
          {showPwd ? 'Ocultar' : 'Ver'}
        </button>
      </div>
    </div>

    {#if error}
      <div class="error" role="alert" style="margin-top:8px;">{error}</div>
    {/if}

    <div style="margin-top:16px; display:flex; gap:10px;">
      <button class="btn primary" type="submit" disabled={loading || !email || !password}>
        {loading ? 'Entrando…' : 'Entrar'}
      </button>
      <button class="btn" type="reset" on:click={() => { email=''; password=''; error=''; }}>
        Limpiar
      </button>
    </div>
  </form>
</div>

// frontend/src/paginas/Login.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "../lib/axios";             
import "../styles/login.css";
import { saveAuth } from "../lib/auth";

export default function Login() {
  const nav = useNavigate();
  const [form, setForm] = useState({ email: "", password: "" });
  const [showPass, setShowPass] = useState(false);
  const [err, setErr] = useState("");
  const [loading, setLoading] = useState(false);

  const onChange = (k, v) => setForm(f => ({ ...f, [k]: v }));
  const disabled = !form.email || !form.password;

  const submit = async (e) => {
    e.preventDefault();
    setErr("");
    setLoading(true);
    try {
      const { data } = await axios.post("/api/auth/login", form);
      saveAuth({ token: data.token, user: data.user, expiresInSec: data.expires_in });
      nav("/");
    } catch (e2) {
      const msg = e2?.response?.status === 401
        ? "Credenciales incorrectas"
        : (e2?.response?.data?.error || "No se pudo iniciar sesión");
      setErr(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container pag-login">
      <div className="card container-inner">
        <h2>Iniciar sesión</h2>
        <p className="subtitle">Ingresa con tu correo y contraseña</p>

        <form onSubmit={submit} className="form">
          <label className="label">Correo</label>
          <input
            className="input"
            type="email"
            autoComplete="email"
            placeholder="ej: nombre@correo.com"
            value={form.email}
            onChange={(e)=>onChange("email", e.target.value)}
          />

          <label className="label">Contraseña</label>
          <div className="input-wrap">
            <input
              className="input"
              type={showPass ? "text" : "password"}
              autoComplete="current-password"
              placeholder="tu contraseña"
              value={form.password}
              onChange={(e)=>onChange("password", e.target.value)}
            />
            <button type="button" className="toggle" onClick={()=>setShowPass(s=>!s)}>
              {showPass ? "Ocultar" : "Mostrar"}
            </button>
          </div>

          {err && <div className="error">{err}</div>}

          <button className="btn btn-secondary" disabled={loading || disabled}>
            {loading ? "Ingresando..." : "Entrar"}
          </button>
        </form>

        <p className="muted">
          ¿No tienes cuenta? <Link to="/registro">Crear cuenta</Link>
        </p>
      </div>
    </div>
  );
}
